homeassistant:
  # Name of the location where Home Assistant is running
  name: PurpleOgres_home
  # Location required to calculate the time the sun rises and sets
  latitude: 53.864026
  longitude: -1.681606
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 208
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London


# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

#emulated_hue:
#  expose_by_default: false
#  exposed_domains:
#    - switch

panel_iframe:
  blackpi3:
    title: 'blackpi3'
    url: 'http://192.168.3.120'
  blackpi2:
    title: 'blackpi2'
    url: 'http://192.168.3.125'   
  cameras:
    title: 'cameras'
    url: 'http://192.168.3.225:8000'
    
recorder:
  purge_days: 14
  db_url: !secret db_connection
  
http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.3.0/24
zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 30
  icon: mdi:home
  
zone 2:
  name: Work_Rich
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 30

# mqtt broker
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password
  protocol: 3.1
  birth_message:
    topic: "tele/hass1/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/hass1/LWT"
    payload: "Offline"
    qos: 1
    retain: true  

notify:
  - name: rich
    platform: pushbullet
    api_key: !secret push_key
    
# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# menu itemsGroups
group: !include groups.yaml

#components

light: !include_dir_merge_list lights

sensor: !include_dir_merge_list sensors

device_tracker: !include_dir_merge_list trackers

switch: !include_dir_merge_list switches

media_player: !include_dir_merge_list players

binary_sensor: !include binary_sensors.yaml

remote:
  - platform: harmony
    name: Front room Harmony
    host: 192.168.3.140


# Automation components

sun:

ifttt:
   key: !secret ifttt_key

#script: !include scripts.yaml

automation: !include_dir_merge_list automation
#!include automations.yaml
#!include_dir_merge_list automation

config:





